version: '3.9'

services:
  web-django:
    image: irwanalamsyah/defas-django-docker
    container_name: defasoil
    build: .
    volumes:
      - .:/defas-django-docker
    ports:
    - "8080:8080"
    command: python3 manage.py runserver 0.0.0.0:8080

  db-postgres:
    image: postgres:13
    ports:
    - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgres/data/
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"

volumes:
  postgres_data: