version: '3.9'

services:
  web-django:
    image: irwanalamsyah/defas-django-docker
    container_name: defasoil
    build: .
    volumes:
      - .:/defas-django-docker
    ports:
    - '8080:8080'
    command: python3 manage.py runserver 0.0.0.0:8080
